# 391 config

# Information about range-finder data
scan_num: 1 # How many scans to use
max_range: -1 # Sensor max range (m)

# Bounds on map height
min_z: 0
max_z: 0

original_size: true
predict: false
